"""Add users table

Revision ID: 002
Revises: 001
Create Date: 2026-02-22

Roles: admin | operator | user
  - admin    — full control; can manage operators and users
  - operator — data provider / analyst; can ingest and annotate
  - user     — read-only viewer; future subscribe-API tier

Uses VARCHAR + CHECK CONSTRAINT instead of a native PostgreSQL enum
so the migration is idempotent and compatible with asyncpg.
"""

import sqlalchemy as sa

from typing import Sequence, Union
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_VALID_ROLES = ("admin", "operator", "user")


def upgrade() -> None:
    # Drop any orphaned users table from a previous autogenerated migration.
    op.execute("DROP TABLE IF EXISTS users CASCADE")

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("username", sa.String(100), unique=True, nullable=False),
        sa.Column("email", sa.String(255), unique=True, nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column(
            "role",
            sa.String(50),
            nullable=False,
            server_default="user",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "role IN ('admin', 'operator', 'user')",
            name="ck_users_role",
        ),
    )


def downgrade() -> None:
    op.drop_table("users")
