[package]
name = "clickhouse-binary"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clickhouse-process"
path = "src/main.rs"

[dependencies]
config = { path = "../config" }
sinks = { path = "../sinks" }
pipeline = { path = "../pipeline" }
observability = { path = "../observability" }
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
eyre = "0.6"
metrics = "0.24"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
